matrix:
  include:
  - stage: Tox
    language: 'python'
    python:
    - "3.6"
    install: pip install tox-travis
    script: tox
  - stage: Vue
    language: 'node_js'
    node_js:
      - 10
    install:
    - pip install -r requirements
    - cd src/main/vue/client
    - npm ci
    script:
    - python ../../python/server/main.py &
    - npm run dev &
    - npm test
