matrix:
  include:
  - stage: Tox
    language: 'python'
    python:
    - "3.6"
    os:
      - linux
      - windows
      - osx
    install: pip install tox-travis
    script: tox
  - stage: Vue
    language: 'node_js'
    install:
    - cd src/main/vue/client
    - npm ci
    script: npm test