matrix:
  include:
     - stage: Tox
       language: 'python'
       install: pip install tox-travis
       script: tox
     - stage: Vue
       language: 'node_js'
       install:
         - cd src/main/vue
         - npm ci
       script: npm test