matrix:
  include:
  - stage: Tox
    language: 'python'
    python:
    - "3.6"
    install: pip install tox-travis
    script: tox
  - stage: Vue
    language: 'node_js'
    install:
    - cd src/main/vue/client
    - npm install
    before_script:
    - python ..\\..\\python\\server\\main.py &
    - npm run dev &
    script: npm test