matrix:
  include:
  - stage: Tox
    language: 'python'
    python:
    - "3.6"
    install: pip install tox-travis
    script: tox
  - stage: Vue
    language: 'node_js'
    node_js:
      - 10
    install:
    - cd src/main/vue/client
    script:
    - npm test
    - python ..\\..\\python\\server\\main.py &
    - npm run dev &